### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by msimonc** [alicoding/react-webpack-babel#12]
Hi, Thanks for this,  I get this in console log.  I've pulled the latest:

Warning: React.render is deprecated. Please use ReactDOM.render from require('react-dom') instead.

**Comment by alicoding** [comment]
@msimonc thanks for filing the issue. I have updated the repo to use `react-dom` here https://github.com/alicoding/react-webpack-babel/commit/f8797b847598f1b9f7dbbc2828179f564b40a3ea
