### ISSUE TITLE
Importing react components

### ISSUE THREAD

**Issue by sach2211** [alicoding/react-webpack-babel#120]
Hi, 
Right now all the react stuff is inside index.jsx
Any idea about how I can include a component (for eg. 'Basic'  defined in '/views/basic.jsx') and render it ?

I tried using import statement (`import Basic from  './views/basic.jsx'`) in index.jsx, but it doesn't work.

**Comment by alicoding** [comment]
I just did it locally and it's working fine for me?

This is how I did it.

Created `views/basic.jsx`

```
import React from 'react';

class Basic extends React.Component {
	render() {
		return (
			<div>This is just a basic component.</div>
		);
	}
}

export default Basic;
```

Then in my `src/index.jsx`

I loaded this

```
import Basic from './views/basic.jsx';
```

And just use it like normal component e.g.

```
<Basic/>
```

**Comment by sach2211** [comment]
Thanks, I found my mistake. 👍
