### ISSUE TITLE
ES6 / JS jsx

### ISSUE THREAD

**Issue by msimonc** [alicoding/react-webpack-babel#13]
My idea is to build my JSX components in ES6, but most open sourced components out there are in JS, so I need a webpack setup that handles both.  Would the file extension be different? Do you handle this now?  Thanks

**Comment by alicoding** [comment]
Loading an external library in `js` shouldn't matter here I believe. The only thing webpack will really help you here is allowing you to write in ES6 or `<` and bundle them together for you. So, really to answer your question would be depend on the library/components that you are trying to include in your project. :)

**Comment by msimonc** [comment]
But a project could have some JSX components in old JS and others in ES6.
Actually Babel is allowing ES6, but it is also compiling JSX.
So how to get Babel to compile JS JSX...

It would be great if your project had a separate app folder and index.html is in it.

Thanks from Sydney,

**Comment by alicoding** [comment]
The easiest way I can think of right now is to add another loader to your `webpack.config.js` file

https://github.com/alicoding/react-webpack-babel/blob/master/webpack.config.js#L18-L25

```
            {
                test: /\.jsx?$/,
                exclude: /(node_modules|bower_components)/,
                loaders: ['react-hot', 'babel'],
            },
```

The above code will allow `babel` to compile old JS and ES6 for any `.jsx` file, but if you want support for both `js` and `jsx` you can just include another `.js` or write a regex that will work for both `jsx` and `js` for one loader:

```
            {
                test: /\.jsx?$/,
                exclude: /(node_modules|bower_components)/,
                loaders: ['react-hot', 'babel'],
            },
            {
                test: /\.js?$/,
                exclude: /(node_modules|bower_components)/,
                loaders: ['react-hot', 'babel'],
            },
```

or the regex like I said :)

**Comment by msimonc** [comment]
Not working for this JS: (React is undefined or there is a TypeError in the terminal).  I set is as the entry point instead of index.jsx.

```
var Counter = React.createClass({
	getInitialState: function () {
		return { clickCount: 0 };
	},
	handleClick: function () {
		this.setState(function(state) {
			return {clickCount: state.clickCount + 1};
		});
	},
	render: function () {
		return (<h2 onClick={this.handleClick}>Click me! Number of clicks: {this.state.clickCount}</h2>);
	}
});
ReactDOM.render( <Counter />, document.getElementById('message'));
```

**Comment by alicoding** [comment]
I just tested this and it's working for me:

```
import React from 'react';
import ReactDOM from 'react-dom';

var Counter = React.createClass({
    getInitialState: function () {
        return { clickCount: 0 };
    },
    handleClick: function () {
        this.setState(function(state) {
            return {clickCount: state.clickCount + 1};
        });
    },
    render: function () {
        return (<h2 onClick={this.handleClick}>Click me! Number of clicks: {this.state.clickCount}</h2>);
    }
});

ReactDOM.render(<Counter/>, document.querySelector("#myApp"));
```

Make sure you include these two:

```
import React from 'react';
import ReactDOM from 'react-dom';
```

**Comment by msimonc** [comment]
Nice!  But I still had a problem with 'source-map' because test: /\.js?$/ matches every file in the project!? So I renamed to .js5, changed to test: /\.js5?$/ and added '.js5' to resolve.extensions.

Thanks for your help!  Now I can require JS coded components!

**Comment by alicoding** [comment]
nice! Maybe you can also do this? `.js.?$` to get `.jsx` and `.js` to work?
