### ISSUE TITLE
webpack.optimize.DedupePlugin

### ISSUE THREAD

**Issue by katopz** [alicoding/react-webpack-babel#138]
Hi,

I'm curious that why `webpack.optimize.DedupePlugin` is not include in production config?

Thanks for awesome work.

**Comment by alicoding** [comment]
@katopz สวัสดีครับ | Thanks for raising this issue. I will have pull request to fix this :)

**Comment by alicoding** [comment]
This is done :) ขอบคุณมากครับ :)
