### ISSUE TITLE
Add eslint-plugin-react to package.json

### ISSUE THREAD

**Issue by Regaddi** [alicoding/react-webpack-babel#146]
Hi,

currently `eslint-plugin-react` is not listed `package.json`.
This leads to some problems with [Atom](atom.io) not finding this module.
Manually adding eslint-plugin-react with `npm i --save-dev eslint-plugin-react` solves that problem.

Best regards,
Chris

**Comment by alicoding** [comment]
Hey! Thank you so much for filling an issue. I have updated the file and its now on master 💃
