### ISSUE TITLE
Missing loader

### ISSUE THREAD

**Issue by TeodorKolev** [alicoding/react-webpack-babel#147]
Hi, I have install `npm install semantic-ui --save` and I got "You may need an appropriate loader to handle this file type" for font files and png file? Is there some remedy for this?

**Comment by TeodorKolev** [comment]
What is that STR?

**Comment by alicoding** [comment]
You'll probably need to add loader for `.js` file

```
	{
		test: /\.js?$/,
		exclude: /(node_modules|bower_components|public)/,
		loaders: ['react-hot']
	},
```

Or edit the regex for `jsx` to also look for `js`

**Comment by TeodorKolev** [comment]
This repo has problem loading fonts

**Comment by alicoding** [comment]
@TeodorKolev have you figured out the problem? because its working fine for me here.... try to nuke your npm_modules and try again.

**Comment by TeodorKolev** [comment]
Yes, after nuke node_nodules, problem is fixed

**Comment by alicoding** [comment]
Awesome!
