### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by brianbier** [alicoding/react-webpack-babel#159]
Hey I was trying to understand how the webpack auto reload is working. 
I know your using a webpack-dev-server, but what part of your code is forcing the reload to happen when you edit a component?

Thanks in advance. Any resources is much appreciated.

**Comment by alicoding** [comment]
Hi,

So the hot-loader works based on this line here https://github.com/alicoding/react-webpack-babel/blob/master/webpack.config.js#L43

Basically, it just wait for file changes and that's the entry point, so anything that file is loaded will be watched as well.

Hope this help?

**Comment by brianbier** [comment]
Hey, Thanks for your response. 

So what exactly is the HtmlWebpackPlugin doing?

**Comment by alicoding** [comment]
@brianbier its basically load in an HTML file and replace it with variables and kind of compiling https://github.com/ampedandwired/html-webpack-plugin

**Comment by brianbier** [comment]
@alicoding Got it. Thanks so much. All that was helpful.

**Comment by alicoding** [comment]
You're welcome :)
