### ISSUE TITLE
webpack-dev-server: Permission denied

### ISSUE THREAD

**Issue by jrichardsz** [alicoding/react-webpack-babel#177]
Hi. Your repo is very usefull but I cant install it :(
My steps was : 
1.- clone
2.- npm install 
3.- npm start and the error after this command is:

```
root@abcde:/some_folder/react-webpack-babel# npm start
react-webpack-babel@0.0.3 start /some_folder/react-webpack-babel
webpack-dev-server --progress --profile --colors

sh: 1: webpack-dev-server: Permission denied

npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "node" "/user/apps/node-v4.2.3-linux-x64/bin/npm" "start"
npm ERR! node v0.10.37
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! react-webpack-babel@0.0.3 start: `webpack-dev-server --progress --profile --colors`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the react-webpack-babel@0.0.3 start script 'webpack-dev-server --progress --profile --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-webpack-babel package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --progress --profile --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-webpack-babel
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-webpack-babel
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /some_folder/react-webpack-babel/npm-debug.log
```

I have several months developing whit node and npm so my node and npm are correct!

node version:v4.2.3
npm version : 3.10.9
linux info : 14.04.1-Ubuntu

Thanks.

**Comment by alicoding** [comment]
hmmm this is interesting since I never face an issue with permission before... this seems like the port is being blocked by your system.

**Comment by jrichardsz** [comment]
Please where can I configure the port of webpack?
I tried in windows 7 , and works!!
Thanks in advance.

**Comment by k3a** [comment]
Hi, you can set port using environmental variable like this:
PORT=3333 npm start

or edit default port in the webpack.config.js

**Comment by chriswingler** [comment]
Did you `sudo npm install` your project folder?

Try `sudo chown <user> <directory>` to fix.

**Comment by alicoding** [comment]
This is not an issue to the project or module itself, so I'm closing this.

**Comment by dloret** [comment]
Hi, I got this issue also in this precise configuration:

- I created the project repo in my dropbox, on Windows 10 (professional) laptop
- I installed the npm dependencies and created package.json + webpack.config.js on Windows 10
- I loaded the project on Visual Studio Code on Linux and ran "npm start" from Fedora 25 (personal laptop)

It could be related to the fact the config (global versus local) installation of some packages is not the same in the 2 environments (windows vs linux). After simply deleting the node_modules folder, without changing the config files, everything was back to normal again.

**Comment by k3a** [comment]
Thanks for letting us know. There can be OS differencies (noticed some file watching package is not installed on some OS for example).

Here Permission denied probably meant an executable script file did not have 'execute' mode enabled. Windows file systems like NTFS do not support unix permissions. Maybe chmod a+x <pathToFile> would have fixed it.

In any case, deleting and reinstalling npm modules should always work.

**Comment by jamiehutber** [comment]
> In any case, deleting and reinstalling npm modules should always work.
Bingo! :+1: 
I copied the files over from my windows machine to `Mint`

**Comment by ijajmulani** [comment]
1. Remove `node_modules` and run `npm install` its will work.
2. If above line doesnot work then remove `package-lock.json` and run `npm install`

**Comment by Xhyen** [comment]
> 1. Remove `node_modules` and run `npm install` its will work.
> 2. If above line doesnot work then remove `package-lock.json` and run `npm install`
> 
> This issue only occur in linux not in windows.
> I don't know reason behind of this.

thank you for help 👍

I solved the problem

**Comment by Twopothead** [comment]
[why-is-permission-denied-for-npm-start-using-node-dev](https://unix.stackexchange.com/questions/109485/why-is-permission-denied-for-npm-start-using-node-dev)
```bash
sudo chmod 755 -R node_modules/
```
It solved my problem without having to remove node_modules folder.

**Comment by jedster1111** [comment]
For me the issue was I hadn't actually installed `webpack-dev-server`, I'd only installed `webpack` and `webpack-cli`.
```sh
yarn add -D webpack-dev-server
```
The above solved it for me. Also I'm running in WSL.
