### ISSUE TITLE
hmr problem

### ISSUE THREAD

**Issue by AgentChris** [alicoding/react-webpack-babel#182]
if make modification is keep refreshing

**Comment by alicoding** [comment]
what is HMR?

**Comment by k3a** [comment]
HMR = Hot module reload - it is implemented using react-hot-loader + webpack's devserver hot reload.

**Comment by alicoding** [comment]
👍 @k3a is your PR ready to be review/tested?

**Comment by k3a** [comment]
yep I tested my PR, it does hot reloading correctly

**Comment by alicoding** [comment]
Thank you so much @k3a for the fix!

**Comment by k3a** [comment]
NP :) I accidentally noticed the Issue so decided to look into it. Btw I made a similar starter for angular2 https://github.com/k3a/angular2-simple-starter (mainly for myself but everyone is free to use it).

**Comment by alicoding** [comment]
@k3a I was going to create that since my workplace also started to use angular2, but in this case I will contribute to yours instead :D
