### ISSUE TITLE
Had to add css loader prefix in app.jsx to successfully complete webpack process

### ISSUE THREAD

**Issue by ilazarte** [alicoding/react-webpack-babel#197]
from:
import 'bootstrap/dist/css/bootstrap.min.css';

to:
import 'css!../node_modules/bootstrap/dist/css/bootstrap.min.css';

otherwise works great, thanks.

**Comment by alicoding** [comment]
Hi,

Do you mind create a pull request with the fix?

Thanks!

**Comment by shershen08** [comment]
Even with the plugin prefix does not work for me. Took a fresh cloned repo, then` npm install` and  and installed only bootstrap (` npm i bootstrap --save`)
Added this to the component like so
```
import styles from './index.scss';
import React from 'react';
import 'css!../node_modules/bootstrap/dist/css/bootstrap.css';

export default class App extends React.Component {
  render() {
    return (
      <div>
```
After `npm start` I get the following
```
ERROR in ./~/css-loader!./~/bootstrap/dist/css/bootstrap.css
Module build failed: Unknown word (5:1)

  3 | // load the styles
  4 | var content = require("!!./../../../css-loader/index.js!./bootstrap.css");
```
<img width="743" alt="screen shot 2016-12-03 at 19 22 19" src="https://cloud.githubusercontent.com/assets/1363772/20861340/e93f3d06-b98d-11e6-8087-5443f28929fc.png">

**Comment by alicoding** [comment]
There seem to be a bug in `css-loader` module itself... I saw this https://github.com/webpack/css-loader/issues/362 issue and using `import 'style!../node_modules/bootstrap/dist/css/bootstrap.css';` instead of `css` prefix works.

**Comment by alicoding** [comment]
Closing this unless we can do anything to make this better...

**Comment by wzup** [comment]
I have similar issue:
```
ERROR in ./~/css-loader!./assets/sass/foo.css
Module build failed: Unknown word (1:1)

> 1 | exports = module.exports = require("./../../node_modules/css-loader/lib/css-base.js")();
    | ^
  2 | // imports
  3 |
  4 |

Syntax Error: Unknown word (1:1)

> 1 | exports = module.exports = require("./../../node_modules/css-loader/lib/css-base.js")();
    | ^
  2 | // imports
  3 |
  4 |

    at C:\Users\user\app\node_modules\css-loader\lib\processCss.js:219:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
 @ ./assets/js/react/dev/MyCustomSlider.js 47:0-22
```

**Comment by alicoding** [comment]
sadly css-loader hasn't fixed their issue yet :(

**Comment by gulshanzealous** [comment]
I had the same error. css-loader is not working. Replaced and style-loader worked instantly. The following works : 
 <code > import "style-loader!../styles/main.css"; </code>
