### ISSUE TITLE
Folders named "public*" will break the application

### ISSUE THREAD

**Issue by LeonardoGentile** [alicoding/react-webpack-babel#213]
Hello,
I've been banging my head for two hours about this until I discovered that if there is any folder inside the src one that starts with `public*` then webpack or babel (not sure) will throw an error like this:
```
ERROR in ./src/publicSection/PublicLayout.jsx
Module parse failed: /my/path/src/publicSection/PublicLayout.jsx Unexpected token (7:12)
You may need an appropriate loader to handle this file type.
...
```
I guess this has something to do with the jsx section in `webpack.loaders.js` where inside the `exclude` field I can see a `public` regex.
I guess this is wrong because probably you wanted to exclude anything within a `public` folder BUT outside `src`, isn't it? Also the regex doesn't match `public` exactly, it will match anything starting with public.

I don't have much experience with webpack and babel to fix this myself

**Comment by alicoding** [comment]
Hi,

You are correct in regard the regex was trying to match any name with `public` in it for the array of paths when the loaded is trying to run the test against. I will try to see if I can update the regex to be more exact here or maybe check for something that ends with slash to exclude instead like `public/`

**Comment by alicoding** [comment]
Fixed by this https://github.com/alicoding/react-webpack-babel/commit/cfde2b276a2a15def446ba00852cffea9b20eb9f thanks for raising the issue 👍
