### ISSUE TITLE
Css don't apply to react components

### ISSUE THREAD

**Issue by andylaci** [alicoding/react-webpack-babel#241]
Hello,
don't know if I am doying something wrong, but I imported partial scss files into index.scss file and written few react components included into app.js and the styles doesn't aply to them. Is it some strange behaviour, or I have to include styles into every single react subcomponent?
What I might be doying wrong? I was inspecting elements and no rules are applied to html elements, but they can be found in bundle.js

my folder structure looks something like this:

├── src
│   ├── app.jsx
│   ├── components
│   │   ├── QuoteInputs.js
│   │   └── QuoteResult.js
│   ├── images
│   ├── index.jsx
│   ├── styles
│   │   ├── common
│   │   │   ├── base.scss
│   │   │   ├── mixins.scss
│   │   │   ├── overrides.scss
│   │   │   └── variables.scss
│   │   ├── components
│   │   │   └── QuoteInputs.scss
│   │   ├── index.scss
│   │   └── layouts
│   │   └── main.scss
│   └── template.html
├── webpack.config.js
├── webpack.loaders.js
├── webpack.production.config.js
└── yarn.lock

**Comment by alicoding** [comment]
Hi,

I just create something similar and it's working okay for me...
```
.
├── LICENSE
├── README.md
├── confirmation.html
├── package.json
├── postcss.config.js
├── public
│   ├── 1bd2a0296194d63b75ce7727ddd3e517.css
│   ├── e31d314d13b74210622c.js
│   └── index.html
├── src
│   ├── app.jsx
│   ├── index.jsx
│   ├── index.scss
│   └── template.html
├── styles
│   ├── common
│   │   └── button.scss
│   ├── index.scss
│   └── main.scss
├── webpack.config.js
├── webpack.loaders.js
├── webpack.production.config.js
└── yarn.lock
```
Now, this is how I used it:

`app.jsx`
```
import styles from '../styles/index.scss';
import React from 'react';

export default class App extends React.Component {
  render() {
    return (
      <div>
        <h1>It Works!</h1>
        <p>This React project just works including <span className={styles.redBg}>module</span> local styles.</p>
        <p>Enjoy!</p>
      </div>
    )
  }
}
```

and `index.scss`
```
@import 'main';
@import 'common/button'
```
and in `button.scss`
```
.redBg {
    background-color: red;
    border-radius: 5px;
    color: white;
    padding: 5px;
}
```

**Comment by andylaci** [comment]
I didn't build it yet, just using npm start

**Comment by alicoding** [comment]
I tried with `npm run dev`

**Comment by andylaci** [comment]
I have the same result with `npm run dev`, don't know how to debug this, changed port 8888 to 4141 btw, but it should't affect this

**Comment by alicoding** [comment]
And did you require `index.scss` in your `jsx` file and use it similar to how I did it?

**Comment by juanhenriquez** [comment]
I have the same problem as @andylaci, it seems that webpack adds a strange name to the classes that are created in index.scss

```javascript 
import React from 'react';

class HomePage extends React.Component {
  render () {
    return (
      <div>
        <p className="bg-container">Hola</p>
      </div>
    );
  }
}

export default HomePage;
```

```css
*, *::after, *::before {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

.bg-container {
  background-color: red!important;
}
```

**Comment by julesmoretti** [comment]
@juanhenriquez @andylaci - So in the webpack.config file try this:

```
// local scss modules
loaders.push({
  test: /\.scss$/,
  exclude: /[\/\\](node_modules|bower_components|public\/)[\/\\]/,
  loaders: [
    'style?sourceMap',
    // 'css?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]&sourceMap',
    'css?modules&importLoaders=1&localIdentName=[local]',
    'postcss',
    'sass'
  ]
});
```

For me the issue I am trying to fix now is how to load Bootstrap properly because it is not being picked up as is.

**Comment by andylaci** [comment]
thanks @julesmoretti , I solved it finally with webpack fixing like this:
```
// local scss modules
loaders.push({
	test: /\.scss$/,
	exclude: /[\/\\](node_modules|bower_components|public\/)[\/\\]/,
	loaders: ['style', 'css?sourceMap', 'postcss', 'sass?sourceMap']
});
```

still curious why there was some versioning and nesting system integrated. What for was it good?

**Comment by julesmoretti** [comment]
No idea on my end why.

**Comment by alicoding** [comment]
Hey @julesmoretti and @andylaci I have change the way how it's being compiled in this https://github.com/alicoding/react-webpack-babel/commit/03405455e6b2b228914703e9f6dcdb2995616b58 and would love it if you guys can test to see if it works the way you expect it to be now.

**Comment by julesmoretti** [comment]
@alicoding - this does not work. If you try `npm run build` and try to open the index.html in the public dir, nothing load.

**Comment by alicoding** [comment]
@julesmoretti the path is wrong in the output file is why the `.js` and `.css` is not loading when you run `npm run build` since you are going to serve your static file based on your need here e.g using expressjs to load them.

**Comment by julesmoretti** [comment]
@alicoding - So I tried running the index.html using node and it is not working still, I get:

```
1f9848b….js:1 Uncaught Error: Minified React error #37; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=37 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at n (1f9848b….js:1)
    at Object._renderNewRootComponent (1f9848b….js:21)
    at Object._renderSubtreeIntoContainer (1f9848b….js:21)
    at render (1f9848b….js:21)
    at Object.<anonymous> (1f9848b….js:21)
    at Object.<anonymous> (1f9848b….js:21)
    at t (1f9848b….js:1)
    at Object.<anonymous> (1f9848b….js:1)
    at t (1f9848b….js:1)
    at 1f9848b….js:1
```

This is node file I used to load the index.html:

```
const path = require('path');
const compression = require('compression');
const express = require('express');

const app = express();

app.set('port', (process.env.PORT || 7000));

app.use(compression());

app.use(express.static(path.join(__dirname, '/public')));

app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'public/index.html'))
});

app.listen(app.get('port'), (err) => {
  if (err) {
    console.log(err);
  }
  console.info('==> Listening on port %s.', app.get('port'));
});
```

Let me know if you can see what the missing bits are :)

**Comment by alicoding** [comment]
@julesmoretti this is the fix https://github.com/alicoding/react-webpack-babel/commit/cdc71e7220343db5c2a083077d3d1475b466e477 sorry about that.
