### ISSUE TITLE
AirBnB Eslint integration?

### ISSUE THREAD

**Issue by julesmoretti** [alicoding/react-webpack-babel#248]
Hello everyone. 

I would love it if you could help me integrate the AirBnb Eslint standards please :)

Could you help me with that?

Thank you.

Jules

**Comment by alicoding** [comment]
Give this branch a shot https://github.com/alicoding/react-webpack-babel/tree/airbnb-eslint it might need some more work to make it not have any error but this is a good start :) https://github.com/alicoding/react-webpack-babel/tree/airbnb-eslint

**Comment by julesmoretti** [comment]
@alicoding - This is very cool. Couple of notes:

"eslint-plugin-react" was missing from the devDependencies so `npm i eslint-plugin-react@latest --save-dev`

And then here is a better version of writing the `npm run lint` command I think:
`"lint": "eslint --ext js --ext jsx ./ --ignore-pattern '/node_modules/' --ignore-pattern '/public/' || exit 0",` which will point out some tabbing issues and so on :)

Though ideally I would want it to be able to handle also `scss` files so:
`"lint": "eslint --ext scss --ext js --ext jsx ./ --ignore-pattern '/node_modules/' --ignore-pattern '/public/' || exit 0",`

But that requires additional modules. But overall it seems to work!

**Comment by integral-llc** [comment]
How to execute linting before any build? I'd like to catch any errors any time I save a file and app is rebuild.
Thx

**Comment by alicoding** [comment]
```
      { enforce: 'pre', test: /\.js$/, exclude: /(node_modules|vendors)/, loader: 'eslint-loader' },
```
@integral-llc
