### ISSUE TITLE
Bootstrap 4 integration

### ISSUE THREAD

**Issue by julesmoretti** [alicoding/react-webpack-babel#249]
Hello there, it would be also super cool if you guys had also a bootstrap integration example

**Comment by alicoding** [comment]
I created a branch with Bootstrap4 in it :) https://github.com/alicoding/react-webpack-babel/tree/bootstrap4 give it a shot and let me know.

**Comment by julesmoretti** [comment]
This is cool! And yes looks like it works on the dev side. But the built version does not.

:)
