### ISSUE TITLE
Running application under a subdirectory on Apache

### ISSUE THREAD

**Issue by frankbolviken** [alicoding/react-webpack-babel#250]
Hi,

We are currently struggling with running the application under any subdirectory. From root works fine.
Tried different setups like publicPath etc, but nothing works.
What we had to do, is having an environment variable called BASE:
```
new webpack.DefinePlugin({
			'process.env': {
				NODE_ENV: '"production"',
				BASE: '"/ea"'
			}
		}),
```
And in all route definitions have something like this:
```
<Route path={process.env.BASE + "/blabla"} component={BLA} />
<Route path={process.env.BASE + "/blabla/blabla"} component={BLA2} />
```

However this seems like a dirty fix. Does anything have a complete example of getting this to work, along with a config for Apache html5 mode that also works?

Also tried using the override someone suggests by providing a baseName when creating the History, but having issue when using redux etc. But all these options sounds wrong to me, as it should be possible to deploy the application wherever you want, without having to hardcode any name into the application and do a rebuild. 

Any help would be greatly appreciated!

**Comment by depadiernos** [comment]
Hi. I had this issue too. Found this SO thread: http://stackoverflow.com/questions/37396427/how-to-bundle-a-react-app-to-a-subdirectory-on-a-server

It's a little old but publicPath seems the way to go. Hope that helps.
