### ISSUE TITLE
Any advice for getting SCSS sourcemaps to work?

### ISSUE THREAD

**Issue by cjmosure** [alicoding/react-webpack-babel#255]
I'm using Chrome 56 on macOS 10.12 and can't get any type of sourcemaps to work for javascript or scss.

**Comment by zeachco** [comment]
Hi @cjmosure can we have a bit more details?
is that happening for the build version or the dev version (`npm start` or `npm run build`) ?

from what I tested on Chrome 54 / Linux 64 source maps are showing the *css* source in the build version and the dev version shows the javascript wrappers instead (I guess that's what you mean)

**Comment by zeachco** [comment]
I also noticed the css is injected in the `<head>` to allow hot-reload
![image](https://cloud.githubusercontent.com/assets/1691052/23341849/614b6ece-fc1d-11e6-97a1-a292ec2b642f.png)

I am not sure chrome sourcemaps expect source maps in that case but I'll make some searches about this, this is likely related to my last PR allowing to hot-load the css into the dev version https://github.com/alicoding/react-webpack-babel/pull/253

**Comment by zeachco** [comment]
Found something :

in `webpack.config.js` you may swap between 
```
	loaders: ['style-loader', 'css-loader?importLoaders=1', 'sass-loader'],
```
and
```
	loader: ExtractTextPlugin.extract({fallback: 'style-loader', use : 'css-loader?sourceMap&localIdentName=[local]___[hash:base64:5]!sass-loader?outputStyle=expanded'}),
});
```

`ExtractTextPlugin` allows to keep source map but disable hot module reload for css / sass / less ...
You would have to reload page and lose your app current state.

There is a work around that works for chrome if you want both: you may go back to using `ExtractTextPlugin` in dev and use an extension to dynamically reload css without reloading the page such as `reload CSS` in chrome

![image](https://cloud.githubusercontent.com/assets/1691052/23341919/958d3c48-fc1e-11e6-87f1-b595de1ee0d5.png)

**Comment by cjmosure** [comment]
Thanks for the quick reply. So scss would be nice on the dev build. I tried the config you had provided above, but still not getting sourcemaps. The ExtractTextPlugin option gives me a separate style.css (instead of inlined styles); however, no sourcemaps are created. If I change the devtool option to source-map from eval-source-map, I get sourcemaps generated, but chrome just points to the index.scss, which isn't actually the source scss, it's the compiled style.css, so that doesn't do much. I'm using redux plugin to persist store, so hmr isn't a huge deal. Just looking for useable sourcemaps.

**Comment by alicoding** [comment]
I have this in my webpack2

```
{
    test: /\.scss$/, // files ending with .scss
    use: ['css-hot-loader'].concat(ExtractTextPlugin.extract({
      fallback: 'style-loader',
      use: [{
        loader: 'css-loader',
        options: {
          sourceMap: true
        }
      }, 'postcss-loader?sourceMap=inline', {
        loader: 'sass-loader',
        options: {
          sourceMap: true
        }
      }]
    }))
  }
```
