### ISSUE TITLE
npm run build - do I need to serve index.html from a web server?

### ISSUE THREAD

**Issue by turnerniles** [alicoding/react-webpack-babel#256]
After running npm run build, do I need to host index.html from a web server? Shouldn't I be able to open /public/index.html in a web browser and see 'It Works!'? All that appears is 'Loading...'. If I don't want to use a web sever, how can I reconfigure webpack?

1. Cloned the project
2. npm i
3. npm run dev (works great)
4. npm run build
5. opened /public/index.html in web browser but only 'Loading...' appears

**Comment by alicoding** [comment]
Hi,

The problem here is probably how you are using webserver to serve these static files. I just ran `npm run build` then `cd public` to the directory and use `python -m SimpleHTTPServer 8000` and was able to see the page with the proper stylesheet here.

**Comment by turnerniles** [comment]
Hi Ali, I am pushing up a merge request now.

**Comment by turnerniles** [comment]
@alicoding, let me know what you think... I'm not using a webserver. I just want to host the static index.html which cannot find the bundled css and js file. Perhaps it should be publicPath: './',
