### ISSUE TITLE
Errors in Babel.js instead of Source Code

### ISSUE THREAD

**Issue by BlakeBrown** [alicoding/react-webpack-babel#258]
When there's an error in my source code, Webkit shows us the error in bundle.js instead of the line in the source code that needs to get fixed. This makes development extremely painful.

Reproducible by cloning the repo and changing app.jsx to the following:
```import React from 'react';
import '../styles/index.scss';

export default class App extends React.Component {
  render() {
    return (
      <div styles={styles}>
        <h1>It Works!</h1>
        <p>This React asd just works including <span className="redBg">module</span> local styles.</p>
        <p>Enjoy!</p>
      </div>
    )
  }
}
```

See [this](https://ibb.co/idUGQa) screenshot to see what I'm talking about.

**Comment by alicoding** [comment]
Sorry for missing this threat :( Did you figure out the issue?
