### ISSUE TITLE
error start server

### ISSUE THREAD

**Issue by serjo96** [alicoding/react-webpack-babel#262]
I do not know what happened, but today at first there was an error from the babel old version of node JS. I updated from 7 to 8 node, now he swears at the server startup, what can advise?
console:

`D:\work\react-s>npm start

> react-webpack-babel@0.0.3 start D:\work\react-s
> webpack-dev-server --progress --profile --colors

 10% building modules 1/1 modules 0 activeevents.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8888
    at Object.exports._errnoException (util.js:1016:11)
    at exports._exceptionWithHostPort (util.js:1039:20)
    at Server.setupListenHandle [as _listen2] (net.js:1307:14)
    at listenInCluster (net.js:1355:12)
    at doListen (net.js:1481:7)
    at _combinedTickCallback (internal/process/next_tick.js:105:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-webpack-babel@0.0.3 start: `webpack-dev-server --progress --profile --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-webpack-babel@0.0.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2017-06-14T18_16_48_660Z-debug.log
`

log:
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.0.3
3 info using node@v8.1.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-webpack-babel@0.0.3~prestart: react-webpack-babel@0.0.3
6 silly lifecycle react-webpack-babel@0.0.3~prestart: no script for prestart, continuing
7 info lifecycle react-webpack-babel@0.0.3~start: react-webpack-babel@0.0.3
8 verbose lifecycle react-webpack-babel@0.0.3~start: unsafe-perm in lifecycle true
9 verbose lifecycle react-webpack-babel@0.0.3~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\work\react-s\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Brackets\command;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\nodejs\;C:\Users\User\AppData\Local\Microsoft\WindowsApps;C:\Users\User\AppData\Roaming\npm
10 verbose lifecycle react-webpack-babel@0.0.3~start: CWD: D:\work\react-s
11 silly lifecycle react-webpack-babel@0.0.3~start: Args: [ '/d /s /c',
11 silly lifecycle   'webpack-dev-server --progress --profile --colors' ]
12 silly lifecycle react-webpack-babel@0.0.3~start: Returned: code: 1  signal: null
13 info lifecycle react-webpack-babel@0.0.3~start: Failed to exec start script
14 verbose stack Error: react-webpack-babel@0.0.3 start: `webpack-dev-server --progress --profile --colors`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid react-webpack-babel@0.0.3
16 verbose cwd D:\work\react-s
17 verbose Windows_NT 10.0.15063
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 verbose node v8.1.1
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error react-webpack-babel@0.0.3 start: `webpack-dev-server --progress --profile --colors`
23 error Exit status 1
24 error Failed at the react-webpack-babel@0.0.3 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]`

**Comment by alicoding** [comment]
`Error: listen EADDRINUSE 127.0.0.1:8888`

It seems like there's already something listening to port `8888` ?

**Comment by serjo96** [comment]
@alicoding Yes, it seems. What can I do?

**Comment by alicoding** [comment]
@serjo96 Depending on your OS 

https://stackoverflow.com/questions/11583562/how-to-kill-a-process-running-on-particular-port-in-linux


https://stackoverflow.com/questions/39632667/how-to-kill-a-currently-using-port-on-localhost-in-windows

**Comment by serjo96** [comment]
@alicoding thanks!
