### ISSUE TITLE
how to set ENV?

### ISSUE THREAD

**Issue by invegat** [alicoding/react-webpack-babel#263]
Tried setting the Environment variable ENV to "debug" and putting  ENV="debug" in a .env root file, still get this message: process.env.ENV is not defined, assuming 'prod' env

**Comment by alicoding** [comment]
Try this

```
new webpack.DefinePlugin({
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development')
}),
```

**Comment by invegat** [comment]
Didn't work, also tried setting ENV and NODE_ENV environmental variables and in the root .env file to "development"

**Comment by alicoding** [comment]
How are you running the app right now? Have you tried doing something like `NODE_ENV=debug npm start` ?

**Comment by invegat** [comment]
Hi, that didn't work either.   I don't see any evidence that either the
environment variables or the root .env file are being used at all.

**Comment by alicoding** [comment]
Can you show some snippet of your code as to how you're using it?

**Comment by invegat** [comment]
in App.jsx:
import Nice from './nice'
import Evil from './evil'
import wrapReactLifecycleMethods, { config } from 'react-component-errors'

config.errorHandler = (errorReport) => {
console.error(`Error in ${errorReport.component}.${errorReport.method}(${(
errorReport.arguments ? '...' : '')}): ${errorReport.error}`, errorReport);
}

@wrapReactLifecycleMethods
export default class App extends React.Component

**Comment by invegat** [comment]
Nice.jsx
const Nice = () =>
<div>
Nice
</div>

export default Nice

**Comment by invegat** [comment]
Evil.jsx
const Evil = () =>
<div>
{this.does.not.exist}
</div>

export default Evil

**Comment by invegat** [comment]
have this div in app.jsx render
<div>
<Nice />
<Evil />
<Nice />
</div>

**Comment by alicoding** [comment]
I don't see where you are using `env` anywhere?

**Comment by invegat** [comment]
Used https://www.npmjs.com/package/dotenv-webpack
[image: Inline image 1]

**Comment by invegat** [comment]
Also tried this
[image: Inline image 1]

**Comment by invegat** [comment]
When I disabled the Grammarly extension the error went away,

**Comment by alicoding** [comment]
So I guess this is not an issue then? Closing for now :)
