### ISSUE TITLE
Can you add a react-router configuration?

### ISSUE THREAD

**Issue by lengziyu** [alicoding/react-webpack-babel#271]
I always make mistakes according to the official [document](https://reacttraining.com/react-router/web/api/Router). Can I add a react-router in this configuration? thank you

**Comment by alicoding** [comment]
If you think it's useful for other then I won't mind accepting a PR at all.

**Comment by pgerochi** [comment]
@lengziyu the master branch now provides an example of basic react-router

**Comment by alicoding** [comment]
Thanks to you @pgerochi ! :D 

@lengziyu I'm going to close this since we've implemented what you've asked for :)
