### ISSUE TITLE
hot reloading of components is not working

### ISSUE THREAD

**Issue by otmjka** [alicoding/react-webpack-babel#272]
It's look like the hot reloading is not working when I changed ex `app.jsx`.

I see messages in the console then I've changed the component, but there are not updates in browser.

![image](https://user-images.githubusercontent.com/5286446/29576799-a02f01a0-8782-11e7-9bf9-7a6bc83f2542.png)

try to update styles and HR work fine with them 

have you the same behavior?

**Comment by Kaishiyoku** [comment]
Same for me.

**Comment by alicoding** [comment]
This should fixed the issue https://github.com/alicoding/react-webpack-babel/commit/dc02bc374f93e915689ff97f74e04cea8d6df250

Thanks for reporting this.
