### ISSUE TITLE
Repo failing to build

### ISSUE THREAD

**Issue by stenmuchow** [alicoding/react-webpack-babel#277]
ERROR in ./src/index.jsx
Module not found: Error: Can't resolve 'react' in '/Users/stenmuchow/Work/react-webpack-babel/src'
 @ ./src/index.jsx 3:13-29
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8888 webpack/hot/dev-server react-hot-loader/patch ./src/index.jsx

ERROR in ./src/index.jsx
Module not found: Error: Can't resolve 'react-dom' in '/Users/stenmuchow/Work/react-webpack-babel/src'
 @ ./src/index.jsx 7:16-36
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8888 webpack/hot/dev-server react-hot-loader/patch ./src/index.jsx

ERROR in ./src/app.jsx
Module not found: Error: Can't resolve 'react' in '/Users/stenmuchow/Work/react-webpack-babel/src'
 @ ./src/app.jsx 28:13-29
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8888 webpack/hot/dev-server react-hot-loader/patch ./src/index.jsx

ERROR in ./src/app.jsx
Module not found: Error: Can't resolve 'sass-loader' in '/Users/stenmuchow/Work/react-webpack-babel'
 @ ./src/app.jsx 32:0-31
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8888 webpack/hot/dev-server react-hot-loader/patch ./src/index.jsx

ERROR in ./node_modules/react-hot-loader/lib/patch.dev.js
Module not found: Error: Can't resolve 'react' in '/Users/stenmuchow/Work/react-webpack-babel/node_modules/react-hot-loader/lib'
 @ ./node_modules/react-hot-loader/lib/patch.dev.js 7:12-28
 @ ./node_modules/react-hot-loader/lib/patch.js
 @ ./node_modules/react-hot-loader/patch.js
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8888 webpack/hot/dev-server react-hot-loader/patch ./src/index.jsx

ERROR in ./node_modules/react-hot-loader/lib/AppContainer.prod.js
Module not found: Error: Can't resolve 'react' in '/Users/stenmuchow/Work/react-webpack-babel/node_modules/react-hot-loader/lib'
 @ ./node_modules/react-hot-loader/lib/AppContainer.prod.js 13:12-28
 @ ./node_modules/react-hot-loader/lib/AppContainer.js
 @ ./node_modules/react-hot-loader/lib/index.prod.js
 @ ./node_modules/react-hot-loader/lib/index.js
 @ ./node_modules/react-hot-loader/index.js
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8888 webpack/hot/dev-server react-hot-loader/patch ./src/index.jsx

ERROR in ./node_modules/react-hot-loader/lib/AppContainer.dev.js
Module not found: Error: Can't resolve 'react' in '/Users/stenmuchow/Work/react-webpack-babel/node_modules/react-hot-loader/lib'
 @ ./node_modules/react-hot-loader/lib/AppContainer.dev.js 11:12-28
 @ ./node_modules/react-hot-loader/lib/AppContainer.js
 @ ./node_modules/react-hot-loader/lib/index.prod.js
 @ ./node_modules/react-hot-loader/lib/index.js
 @ ./node_modules/react-hot-loader/index.js
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8888 webpack/hot/dev-server react-hot-loader/patch ./src/index.jsx

ERROR in ./node_modules/redbox-react/lib/index.js
Module not found: Error: Can't resolve 'react' in '/Users/stenmuchow/Work/react-webpack-babel/node_modules/redbox-react/lib'
 @ ./node_modules/redbox-react/lib/index.js 18:13-29
 @ ./node_modules/react-hot-loader/lib/AppContainer.dev.js
 @ ./node_modules/react-hot-loader/lib/AppContainer.js
 @ ./node_modules/react-hot-loader/lib/index.prod.js
 @ ./node_modules/react-hot-loader/lib/index.js
 @ ./node_modules/react-hot-loader/index.js
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8888 webpack/hot/dev-server react-hot-loader/patch ./src/index.jsx

ERROR in ./node_modules/redbox-react/lib/index.js
Module not found: Error: Can't resolve 'react-dom' in '/Users/stenmuchow/Work/react-webpack-babel/node_modules/redbox-react/lib'
 @ ./node_modules/redbox-react/lib/index.js 22:16-36
 @ ./node_modules/react-hot-loader/lib/AppContainer.dev.js
 @ ./node_modules/react-hot-loader/lib/AppContainer.js
 @ ./node_modules/react-hot-loader/lib/index.prod.js
 @ ./node_modules/react-hot-loader/lib/index.js
 @ ./node_modules/react-hot-loader/index.js
 @ ./src/index.jsx
 @ multi (webpack)-dev-server/client?http://127.0.0.1:8888 webpack/hot/dev-server react-hot-loader/patch ./src/index.jsx

**Comment by alicoding** [comment]
Try run `npm prune` then run `npm install` again? Or run `yarn`

**Comment by alicoding** [comment]
Please reopen if you still seeing an issue...

**Comment by stenmuchow** [comment]
Sorry, havent been able to try again. Thanks!
