### ISSUE TITLE
build js file is too big

### ISSUE THREAD

**Issue by bilguun** [alicoding/react-webpack-babel#288]
Hi,

can anyone help me on this. my build js file is too big, 2MB. 
Is there anyway to make it small?

**Comment by alicoding** [comment]
Is it just from what you have cloned here?

You ran it with production flag, right? Can you provide more details?

**Comment by bilguun** [comment]
Yes just what I've cloned from here.

I've tried with 
`new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('production')
      }
    }),`

and this.

`new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: '"production"'
      }
    }),

Still same.

Here is my dev dependencies.

`"devDependencies": {
    "axios": "^0.17.1",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-jest": "^21.2.0",
    "babel-loader": "^7.1.2",
    "babel-plugin-module-resolver": "^2.7.1",
    "babel-plugin-transform-class-properties": "^6.22.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-runtime": "^6.22.0",
    "css-loader": "^0.26.1",
    "enzyme": "^3.1.0",
    "enzyme-adapter-react-16": "^1.0.1",
    "eslint": "^4.3.0",
    "eslint-plugin-jest": "^20.0.3",
    "eslint-plugin-react": "^7.1.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^0.10.0",
    "html-webpack-plugin": "^2.26.0",
    "i": "^0.3.6",
    "jest": "^21.2.1",
    "jquery": "^3.2.1",
    "loglevel": "^1.4.1",
    "postcss-loader": "^1.2.2",
    "react-bootstrap": "^0.31.5",
    "react-hot-loader": "^3.0.0-beta.7",
    "react-owl-carousel": "^2.2.0",
    "react-router-dom": "^4.1.1",
    "react-router-redux": "^4.0.7",
    "react-spinkit": "^3.0.0",
    "react-sticky": "^6.0.1",
    "react-test-renderer": "*",
    "style-loader": "^0.19.0",
    "url-loader": "^0.5.7",
    "webpack": "^3.6.0",
    "webpack-cleanup-plugin": "^0.4.2",
    "webpack-dashboard": "^0.3.0",
    "webpack-dev-server": "^2.4.1"
  },`

**Comment by alicoding** [comment]
Hi, sorry for the late reply.

I just ran `npm run build` and looking at my `dist` files here
```
➜  react-webpack-babel git:(master) ll public
total 384
-rw-r--r--  1 ali  staff   182K  2 Dec 07:10 e4b7e0eecfefb0586e87.js
-rw-r--r--  1 ali  staff   378B  2 Dec 07:10 index.html
-rw-r--r--  1 ali  staff   124B  2 Dec 07:10 style.css
```

There are really small. Could you try run `npm run build` and look at your `public` to see how big that is?

**Comment by bilguun** [comment]
thanks Ali, mine is still around 2MB.

**Comment by alicoding** [comment]
@bilguun do you mind push yours somewhere so I can try to see what's wrong ?

**Comment by pgerochi** [comment]
@bilguun @alicoding I also see dev dependencies that is currently not in our package.

**Comment by pgerochi** [comment]
If the issue persist again please let us know again, otherwise I think you have a few extra things installed in your project.
