### ISSUE TITLE
Npm run build does not work properly.

### ISSUE THREAD

**Issue by pgerochi** [alicoding/react-webpack-babel#289]
When trying to create a build for the project, the files are compiled properly but looking into the index.html file in the public folder, shows an empty black screen.

**Comment by alicoding** [comment]
Actually, it's working for me?

![screen shot 2017-12-02 at 7 17 37 am](https://user-images.githubusercontent.com/4368149/33515410-f4034f7c-d730-11e7-9cd4-4138bb22f858.png)
