### ISSUE TITLE
Images are not displaying

### ISSUE THREAD

**Issue by danilsitnikov783** [alicoding/react-webpack-babel#294]
Hi! I have a problem. I trying to show image(.png) in img:

`
import duck from './duck.png'; //or const duck = require('./duck.png')
<img src={duck} />
`

Img rendered but not visible. On OS X i can render images only via css background but on win10 I can't. In img src it doesn't works. Haven't any errors. What the problem?

**Comment by danilsitnikov783** [comment]
resolved. I just removed from webpack.config svg&png from loaders and switched in webpack.loaders svg&png from url-loader to file-loader and this works.

**Comment by alicoding** [comment]
Hi,

Do you mind submitting a PR if you think other might benefit the same? With
an example of an image :)

**Comment by danilsitnikov783** [comment]
I'm not sure about OS X now, will know at evening))

**Comment by pgerochi** [comment]
#296 This will fix the issue, I've added a sample in under About.jsx
