### ISSUE TITLE
Remove generated build files

### ISSUE THREAD

**Issue by mrienstra** [alicoding/react-webpack-babel#41]
Specifically:

[bundle.js](https://github.com/alicoding/react-webpack-babel/blob/2c783db473f9951966bff54018daa41e0cd36ef2/public/bundle.js) & [bundle.js.map](https://github.com/alicoding/react-webpack-babel/blob/2c783db473f9951966bff54018daa41e0cd36ef2/public/bundle.js.map)

Happy to make a pull request if you'd prefer.

**Comment by alicoding** [comment]
That would be great! I'm happy to review and merge right away

**Comment by mrienstra** [comment]
Resolved by #42.
