### ISSUE TITLE
Build Blank

### ISSUE THREAD

**Issue by JesterXL** [alicoding/react-webpack-babel#54]
Thanks a lot for this, everything development wise works wonderfully!

When I do a `npm run build`, however, once it completes the site doesn't work. I've tried a simple Express.js server of my own, a simple Python one, nothing. I don't see any script errors, nor network load errors and can see all required files being loaded. I don't think the main app file is run because if I add a simple interval, it never runs. The code IS in the bundle, just not executed.

Any idea why? Assuming this is a webpack issue.

**Comment by alicoding** [comment]
@JesterXL I just tried the same, but I can get it working here?

Just to explain that `npm run build` simply build the `webpack` js file and then you have to statically serve `index.html` file that includes `build.js` file that was build by `webpack`. Try to set up a server that serve `public` directory there :)

```
var express = require('express');
var app = express();

app.use('/', express.static('public'));

app.listen(3000);
```

Another thing to keep in mind here is that `webpack.config.js` is set to be for dev mode at the moment which will not do much at the moment, but at least get you started.

**Comment by JesterXL** [comment]
Yeah, I have about that exact setup with a local Express server, but no dice. Lemme try a new project from master right quick and see what the difference is.

**Comment by holmesal** [comment]
Yep, I'm seeing the same thing with a fresh project just cloned from master. Steps I followed in detail:

* Cloned the project
* `npm i`
* `npm run dev` (works great)
* `npm run build`
* `serve ./public` (simple static web server)

Result:

![image](https://cloud.githubusercontent.com/assets/1147390/14731349/7b24220e-0804-11e6-90c9-377e842ab452.png)

Webpack output from `npm run build`:
![image](https://cloud.githubusercontent.com/assets/1147390/14731366/b1b7e3fa-0804-11e6-8fbe-e8a160d60f69.png)

Other than these issues, this boilerplate looks great! Super minimal. Keep up the great work!

**Comment by holmesal** [comment]
@alicoding - I didn't read your last comment fully. 

> Another thing to keep in mind here is that webpack.config.js is set to be for dev mode at the moment which will not do much at the moment, but at least get you started.

That would explain why the built `bundle.js` is over a meg and includes sockjs and etc 😁 

A webpack production config would be an awesome addition to this project, and I'm sure many people would appreciate it. I'll try to come back and PR once I get my production config up and running.

**Comment by holmesal** [comment]
`Twas easier than I thought ---> #65

**Comment by alicoding** [comment]
This is perfect @holmesal ! Thank you so much for your PR 👍
