### ISSUE TITLE
Docs should mention running "npm install"?

### ISSUE THREAD

**Issue by garyrob** [alicoding/react-webpack-babel#58]
You seem to be making everything perfectly simple, including explaining how to install webpack and the development server globally. But "npm run build" doesn't work unless I do "npm install" first. Seems like it would be simpler and easier to understand for newbies if the docs mentioned the need to do "npm install".

**Comment by alicoding** [comment]
@garyrob I would gladly take a pull request if you can help update the pull request on which steps that you were struggling :)

**Comment by alicoding** [comment]
https://github.com/alicoding/react-webpack-babel/commit/4822efe669552e08de030f2da9bc3e399856990a
