### ISSUE TITLE
Change require to import

### ISSUE THREAD

**Issue by Mizner** [alicoding/react-webpack-babel#66]
`import 'bootstrap/dist/css/bootstrap.min.css';`

**Comment by dehimer** [comment]
Yes, I alse got ERROR in ./~/css-loader!./~/bootstrap/dist/css/bootstrap.css
But import return same error.

**Comment by dehimer** [comment]
I found my problem.
I used node version 0.10.
https://github.com/webpack/css-loader/issues/144

**Comment by alicoding** [comment]
Is this problem still persists? Sorry for the late reply here...

**Comment by dehimer** [comment]
I later versions of node it is good - no problem.

**Comment by alicoding** [comment]
👍
