### ISSUE TITLE
Use Container#walkRules instead.

### ISSUE THREAD

**Issue by brw31415** [alicoding/react-webpack-babel#7]
70% 1/1 build moduleshttp://localhost:8080/
webpack result is served from /
content is served from ./public
 62% 45/51 build modulesContainer#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
4907ms build modules      
10ms seal
11ms optimize
13ms hashing
48ms create chunk assets
16ms additional chunk assets
890ms optimize chunk assets
1ms optimize assets 
16ms emit

**Comment by alicoding** [comment]
@brw31415 Thanks for reporting this. Updated and fixed in here https://github.com/alicoding/react-webpack-babel/commit/8bbfa05944ba8011d74174be14f149fff2f39d64.
