### ISSUE TITLE
Cloud9 Usage

### ISSUE THREAD

**Issue by bduff9** [alicoding/react-webpack-babel#89]
Just wanted to make a note here about getting this to run in [cloud9](https://c9.io).  In case you are not familiar, cloud9 is a cloud VM which can be used for development work.  Cloning a repo into it is a great way to test things out and do dev work right in the browser.

The majority of the instructions were great, however there are two tweaks needed to get this repo to run in c9.  To make it as easy as possible, I will include the full steps here that I followed to get it to run:

1. Sign up for cloud9 and start a new workspace of type nodeJS
2. Delete any files you don't need since space is limited
3. On the command line at the bottom of the screen run:
`git clone https://github.com/alicoding/react-webpack-babel.git`
4. Once done, cd to the new directory:
`cd react-webpack-babel`
5. Install the dependencies:
`npm install`
6. Install webpack:
`npm i webpack-dev-server webpack -g`
7. Open webpack.config.js and change line 8 to:
`'webpack-dev-server/client?https://' + process.env.HOST + ':' + process.env.PORT, // WebpackDevServer host and port`
8. In the server window, give it a name of Webpack, change the Runner to Shell command, the CWD to the react-webpack-babel folder, and enter the Command:
`webpack-dev-server --progress --profile --colors --hot --host $IP --port $PORT`
9.  If all was done correctly, you should be able to click Run and have it run for you.

Steps 7 and 8 are required for Cloud9 since they assign an IP and PORT at runtime.  Hope this helps!

**Comment by alicoding** [comment]
I just updated the [code](https://github.com/alicoding/react-webpack-babel/commit/e9c6795a96a5026b7255bf0d5393a6a79963f6e5) to make it work with c9, but the only problem I'm still facing here is the hot-loading doesn't seem to work after the update...

I'm going to investigate more later once I'm done with my work, but if you can get it working please do let me know.

**Comment by alicoding** [comment]
Ah, so the issue was the URL protocol and mixed content. This should now work if you change it to `http` if you have set it to `http` in webpack config file.

**Comment by alicoding** [comment]
specifically here https://github.com/alicoding/react-webpack-babel/blob/master/webpack.config.js#L12

**Comment by alicoding** [comment]
I'm going to close this ticket unless you believe this still need more work :)
